@rootURL = http://localhost:5021

GET {{rootURL}}/api/books
Accept: application/json

###
GET {{rootURL}}/api/books/2
Accept: application/json

###
POST {{rootURL}}/api/books
Content-type: application/json
{
  "title": "C# Unlocked",
  "author": "Joe Doe",
  "quantity": 1
}

###
PUT {{rootURL}}/api/books/6
Content-Type: application/json
{
  "id": 6,
  "title": "C# eBook",
  "author": "Alen",
  "quantity": 199
}
###
DELETE {{rootURL}}/api/books/4

###
GET {{rootURL}}/api/books/search?title=1984
Accept: application/json

###
GET {{rootURL}}/api/books/search?author=George
Accept: application/json

###
GET {{rootURL}}/api/books/search?title=kill&author=Harper
Accept: application/json

###
POST {{rootURL}}/api/books/2/lend
Accept: application/json

###
POST {{rootURL}}/api/books/2/return
Accept: application/json

###
GET {{rootURL}}/api/books/low-stock?threshold=190
Accept: application/json