// <auto-generated />
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Quantity = 192,
                            Title = "The Great Gatsby",
                            TotalQuantity = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Quantity = 196,
                            Title = "To Kill a Mockingbird",
                            TotalQuantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Quantity = 194,
                            Title = "1984",
                            TotalQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Quantity = 181,
                            Title = "Pride and Prejudice",
                            TotalQuantity = 0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Herman Melville",
                            Quantity = 185,
                            Title = "Moby-Dick",
                            TotalQuantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
